---
# iptables -t nat -A PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
- name: Consul | udp PREROUTING packets
  iptables:
    table: nat
    action: append
    chain: PREROUTING
    protocol: udp
    match: udp
    destination_port: '53'
    jump: REDIRECT
    to_ports: '8600'
    comment: '{{ managed_message }} Consul PREROUTING udp packets'

# iptables -t nat -A PREROUTING -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
- name: Consul | tcp PREROUTING packets
  iptables:
    table: nat
    action: append
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: '53'
    jump: REDIRECT
    to_ports: '8600'
    comment: '{{ managed_message }} Consul PREROUTING tcp packets'

# # iptables -t nat -A OUTPUT -d localhost -p udp -m udp --dport 53 -j REDIRECT --to-ports 8600
# - name: Consul | udp OUTPUT packets
#   iptables:
#     table: nat
#     action: append
#     chain: OUTPUT
#     destination: localhost
#     protocol: udp
#     match: udp
#     destination_port: '53'
#     jump: REDIRECT
#     to_ports: '8600'
#     comment: '{{ managed_message }} Consul OUTPUT udp packets' 

# # iptables -t nat -A OUTPUT -d localhost -p tcp -m tcp --dport 53 -j REDIRECT --to-ports 8600
# - name: Consul | tcp OUTPUT packets
#   iptables:
#     table: nat
#     action: append
#     chain: OUTPUT
#     destination: localhost
#     protocol: tcp
#     match: tcp
#     destination_port: '53'
#     jump: REDIRECT
#     to_ports: '8600'
#     comment: '{{ managed_message }} Consul OUTPUT tcp packets' 

- name: Consul | resolved path
  file:
    path: "/etc/systemd/resolved.conf.d"
    state: directory

- name: Consul | systemd version
  raw: systemctl --version
  register: raw_version

- name: parse systemd version
  raw: "echo {{ raw_version.stdout[8:11] }}"
  register: version

- name: Consul | run template
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf.d/consul.conf
  vars:
    ver: "{{ version.stdout }}"
  notify:
    - restart resolved
