---

- name: Delete Consul out dir
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/network/dummy0.netdev
    - /etc/systemd/network/dummy0.network
    - /etc/consul.d/interfaces.json
    - /etc/dnsmasq.d/consul.conf

- name: Dnsmasq | Remove package
  become: yes
  apt:
    pkg: dnsmasq
    state: absent



- name: Dummy | Bounce systemd-networkd
  become: yes
  service:
    name: systemd-networkd
    state: restarted

# - name: Dummy | Bounce dnsmasq
#   become: yes
#   service:
#     name: dnsmasq
#     state: restarted